### PR TITLE
Skipped failed tests

### PR DESCRIPTION
**Pull request by anmyachev**
I propose so far to skip tests that fall. Thus, it will be possible to work in parallel to correct the tests and, for example, to do implementation of new features.

@fschlimb @Alexander-Makaryev @Vyacheslav-Smirnov what you think about it?

### CODE REVIEW

**Comment by fschlimb** [comment]
Are there any features being worked on that depend on each other or any other non-merged PR?
If not, I do not see how this would help. We can develop features and accompanying tests independently.

**Comment by anmyachev** [comment]
@fschlimb you have, for example, two PRs: #89, #90. It would be great to know if these changes break any tests. In the case when there are already tests in the master that do not pass, it is difficult to track the impact of new changes that will be pushed on the master.

**Comment by fschlimb** [comment]
Our priority right now is to get things stabilized, e.g. fix issues in existing stuff. New features, improvements and optimizations are secondary (or less).

OK, let's be practical. It's probably easier to start from a green state. Let's merge this now. 

However, from then on, we should merge only bug-fixes until all these tests are corrected an enabled.

**Comment by anmyachev** [comment]
> "fix needed" might be better than "needed fix", though.

I'll fix it now

**Comment by anmyachev** [comment]
> Our priority right now is to get things stabilized, e.g. fix issues in existing stuff. New features, improvements and optimizations are secondary (or less).
> 
> OK, let's be practical. It's probably easier to start from a green state. Let's merge this now.
> 
> However, from then on, we should merge only bug-fixes until all these tests are corrected an enabled.

@fschlimb OK I understood

**Pull request merged**
