### PR TITLE
groupby.median

### PR DESCRIPTION
**Pull request by Hardcode84**
My attempt to fix `groupby.median`.

`groupby` uses functions already defined for `series` but run additional pass `agg_distributed_run` to parallelize(?) them. This pass parses original python function and expects very specific function structure (see `_column_mean_impl` for supported example). `series.median` just calls `hpat.hiframes.api.median` and pass cannot process it.

I tried to write separate path in `agg_distributed_run` to skip all parallelization logic and just call provided function but it is incomplete and doesn't work yet.

### CODE REVIEW

**Comment by Hardcode84** [comment]
@shssf @kozlov-alexey FYI

**Comment by shssf** [comment]
@Hardcode84 Is this PR is still in work in progress stage? Is it ready for merge?

**Comment by fschlimb** [comment]
Before merge, please trigger CI with an empty commit or alike.

**Comment by Hardcode84** [comment]
still not ready, no updates so far. I will close it for now

**Pull request closed without merging**
