### PR TITLE
Improve CI builds

### PR DESCRIPTION
**Pull request by Vyacheslav-Smirnov**
- Decrease Azure build matrix (stay Win and OSX num_pes 0, 2)
 - Build only with numpy 1.16 and Python 3.7 (should decrease single build for twice)
 - Move Linux num_pes 0, 1, 2, 3 (3 - allow_failure) to Travis
 - Set time limit for all builds for 2 hours
 - Add coverage
 - Add flake8
 - Add HPAT wheels build and test on Linux
- Skip test_intraday for numpes > 1 due to it hangs on nump_pes 2 and 3

### CODE REVIEW

**Comment by shssf** [comment]
@Vyacheslav-Smirnov As far as I understand this PR is "work in progress" stage.
Please let me know (by removing label WIP) if it ready to review/merge.
Thank you for PR

**Comment by shssf** [comment]
@Vyacheslav-Smirnov And please, squash commits

**Comment by Vyacheslav-Smirnov** [comment]
Hi @shssf , @Alexander-Makaryev ,
The PR is ready for review - Azure checks are passed, Linux num_pes 3 takes too mach time on Travis thus it fails (it is allowed to fail)
Regarding the coverage - there is a link for this job (https://coveralls.io/jobs/54710087) https://travis-ci.com/IntelPython/hpat/jobs/248300955#L5911
For some reason it is not reported in the PR - I will investigate later

I have not done squash because I had to test each commit in CI

**Comment by Vyacheslav-Smirnov** [comment]
Hi,
Have done changes to skip test_intraday only for numpes > 1
@Hardcode84, could you please review and if all it good merge the changes?

**Pull request merged**
