### PR TITLE
Compatibility with python<3.7

### PR DESCRIPTION
**Pull request by fschlimb**
@ehsantn @shssf @Alexander-Makaryev

### CODE REVIEW

**Comment by shssf** [comment]
LGTM

**Comment by Vyacheslav-Smirnov** [comment]
Build with these changes is well for both Python 3.6 and Python 3.7

**Comment by shssf** [comment]
@Vyacheslav-Smirnov yes, it should be.

**Comment by Vyacheslav-Smirnov** [comment]
👍 
So Frank, could you please merge this pull-request?

**Comment by fschlimb** [comment]
We need a volunteer to get our checks green before merging anything else.

**Pull request merged**
